import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    id: 1,
    name: "Sharpy",
    description: "Sharp and small",
    imageUrl: "/small-plant-1.webp",
    category: "small",
    price: 15,
  },
  {
    id: 2,
    name: "Long Sharpy",
    description: "Sharp and long",
    imageUrl: "/small-plant-2.webp",
    category: "small",
    price: 18,
  },
  {
    id: 3,
    name: "Tiny Cactus",
    description: "Sharp and small",
    imageUrl: "/small-plant-3.webp",
    category: "small",
    price: 12,
  },
  {
    id: 4,
    name: "Tiny Sharpy",
    description: "Sharp and tiny",
    imageUrl: "/small-plant-4.webp",
    category: "small",
    price: 16,
  },
  {
    id: 5,
    name: "Solid Leaves",
    description: "All-around solid",
    imageUrl: "/small-plant-5.webp",
    category: "small",
    price: 12,
  },
  {
    id: 6,
    name: "Bordeaux Cactus",
    description: "Colored and spiky",
    imageUrl: "/small-plant-6.webp",
    category: "small",
    price: 15,
  },
  {
    id: 7,
    name: "Lavender-Rose Mix",
    description: "Combination of scents and beauty",
    imageUrl: "/aromatic-plant-1.webp",
    category: "aromatic",
    price: 17,
  },
  {
    id: 8,
    name: "Yellow Rose",
    description: "Beautiful and bright",
    imageUrl: "/aromatic-plant-2.webp",
    category: "aromatic",
    price: 19,
  },
  {
    id: 9,
    name: "Classic Lavender",
    description: "Brigs a familiar scent",
    imageUrl: "/aromatic-plant-3.webp",
    category: "aromatic",
    price: 15,
  },
  {
    id: 10,
    name: "Purple Sharpy",
    description: "A sharpy scent",
    imageUrl: "/aromatic-plant-4.webp",
    category: "aromatic",
    price: 13,
  },
  {
    id: 11,
    name: "Tiny Aromatic Sunflowers",
    description: "Small in size but big in scent",
    imageUrl: "/aromatic-plant-5.webp",
    category: "aromatic",
    price: 19,
  },
  {
    id: 12,
    name: "Varied Sharpies",
    description: "Sharp in all types",
    imageUrl: "/aromatic-plant-6.webp",
    category: "aromatic",

    price: 15,
  },
  {
    id: 13,
    name: "Kyoto",
    description: "Authentic japanese bonsai",
    imageUrl: "/bonsai-plant-1.webp",
    category: "bonsai",
    price: 24,
  },
  {
    id: 14,
    name: "Yokohama",
    description: "Authentic japanese bonsai",
    imageUrl: "/bonsai-plant-2.webp",
    category: "bonsai",
    price: 30,
  },
  {
    id: 15,
    name: "Osaka",
    description: "Authentic japanese bonsai",
    imageUrl: "/bonsai-plant-3.webp",
    category: "bonsai",
    price: 28,
  },
  {
    id: 16,
    name: "Nagoya",
    description: "Authentic japanese bonsai",
    imageUrl: "/bonsai-plant-4.webp",
    category: "bonsai",
    price: 26,
  },
  {
    id: 17,
    name: "Saitama",
    description: "Authentic japanese bonsai",
    imageUrl: "/bonsai-plant-5.webp",
    category: "bonsai",
    price: 35,
  },
  {
    id: 18,
    name: "Kanazawa",
    description: "Authentic japanese bonsai",
    imageUrl: "/bonsai-plant-6.webp",
    category: "bonsai",
    price: 25,
  },
];

const ProductsSlice = createSlice({
  name: "products",
  initialState,
  reducers: {},
});

export default ProductsSlice.reducer;
